### ISSUE TITLE
Can you added some explanation notes?

### ISSUE THREAD

**Issue by Bladefidz** [rioastamal-examples/golang-book-dotcom#1]
Hi!

It is coincidence that I interested to learn Go, but I just can not figured out of how that codes work under the hood. Also, I feel too lazy to read the book which you referred. Can you add some notes to help me understand the codes you provided here?

Thank you in advance,

**Comment by rioastamal** [comment]
Hi,

Sure, but before chapter 6 the concept is simple hence no need much comments/code explanation. Starting from chapter 7 I add comments to remind my self about the code. Hope it helps. 

The book is short and very straightforward - try to read it if you do not understand part of the code.

**Comment by Bladefidz** [comment]
Hi,

Thank you for the response. I will try to read the book.

Cheer,
